# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Blackbeard's Brain"

description: "Trimming My Sails on the Worldwide Web"

email: 'blackbeardsbrain@gmail.com'

#blog logo
logo: "/assets/images/sp_logo.jpg"

# blog cover
cover: "/assets/images/braindump.jpg"

name: 'Eric Smith'
author: 'Eric Smith'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://blackbeardsbrain.com" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@blackbeard_f3'

#fill in disqus shortname to use disqus
#disqus: smithyp-com

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/blackbeard_f3
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/esmith818
    desc:	Fork me on github
#    share_url:
#    share_title:
#    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
